#! /bin/bash/


psql -d fdd2db -c "create table avg_betweenrates_pergenre as select user_id, genre, avg(time_between_rates) as avg from
(select user_id, unnest(array_genres) as genre, time_between_rates from
(select user_id, regexp_split_to_array(genres, '\|') as array_genres, (date-previous_rate)::interval as time_between_rates from
(select movie_id,user_id,row_number() over (partition by user_id order by date asc) row_num, date, lag(date) over (partition by user_id order by date asc) previous_rate,genres,rating from
ratings left join movies on movie_id = id) as sbq1 where previous_rate is not null) as sbq2) as sbq3 where genre != '(no genres listed)' group by user_id, genre order by user_id, genre";

psql -d fdd2db -c "create table genre_limit_decile as select distinct genre, percentile_cont(0.1) within group (order by avg) as decile from avg_betweenrates_pergenre group by genre";

psql -d fdd2db -c "create table users_under_deciles as select * from (select distinct genre, avg, user_id, ntile(10) over (partition by genre order by avg) as decil from avg_betweenrates_pergenre) as sbq1 where sbq1.decil=1 group by genre,avg, user_id, decil order by genre, decil;"

psql -d fdd2db -c "create view repetitions_by_user as select user_id, contador_aparicion from (select user_id, count(user_id) as contador_aparicion from 
(select user_id, avg_betweenrates_pergenre.genre from avg_betweenrates_pergenre join genre_limit_decile on avg_betweenrates_pergenre.genre= genre_limit_decile.genre where avg <= decile) as sbq1 group by user_id) as sbq2 where contador_aparicion >= 2 order by contador_aparicion, user_id;"

psql -d fdd2db -c "select contador_aparicion as generos, count(contador_aparicion) as usuarios_repetidos_endecilbajo from repetitions_by_user group by contador_aparicion;"

psql -d fdd2db -c "select count(distinct user_id) from ratings";

psql -d fdd2db -c "select count(distinct user_id) from repetitions_by_user";

psql -d fdd2db -c "select count(distinct user_id) from users_under_deciles";
